version: "3.9"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - app
      - db
    volumes:
      - ./horoscope:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d

  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/www/mysql
    environment:
      MYSQL_DATABASE: horoscope
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
  app:
    platform: linux/x86_64
    container_name: horoscope
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./horoscope:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
